"""initial schema

Revision ID: 30490a8e2cf7
Revises: 
Create Date: 2026-08-23 20:12:23.351023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30490a8e2cf7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('required_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_service_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category_raw', sa.Text(), nullable=True),
    sa.Column('type_raw', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('service_type', sa.String(length=32), nullable=False),
    sa.Column('rate_rub', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=False),
    sa.Column('refill', sa.Boolean(), nullable=False),
    sa.Column('cancel', sa.Boolean(), nullable=False),
    sa.Column('dripfeed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_service_id')
    )
    op.create_index('ix_services_platform_active', 'services', ['platform', 'is_active'], unique=False)
    op.create_index('ix_services_platform_type_active', 'services', ['platform', 'service_type', 'is_active'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('balance >= 0', name='ck_users_balance_nonnegative'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_referrer_id', 'users', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('cryptobot_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('cryptobot_invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('amount_crypto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_rub_locked', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pay_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cryptobot_invoice_id')
    )
    op.create_index('ix_cryptobot_invoices_status', 'cryptobot_invoices', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.BigInteger(), nullable=False),
    sa.Column('external_order_id', sa.String(length=64), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('charge_rub', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('upstream_cost_rub', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_count', sa.Integer(), nullable=True),
    sa.Column('remains', sa.Integer(), nullable=True),
    sa.Column('upstream_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_open', 'orders', ['last_checked_at'], unique=False, sqlite_where=sa.text("status NOT IN ('completed','canceled','failed','refunded')"))
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_table('balance_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('related_order_id', sa.BigInteger(), nullable=True),
    sa.Column('related_invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_invoice_id'], ['cryptobot_invoices.id'], ),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_balance_tx_user_created', 'balance_transactions', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_balance_tx_user_created', table_name='balance_transactions')
    op.drop_table('balance_transactions')
    op.drop_index('ix_orders_user_created', table_name='orders')
    op.drop_index('ix_orders_open', table_name='orders', sqlite_where=sa.text("status NOT IN ('completed','canceled','failed','refunded')"))
    op.drop_table('orders')
    op.drop_index('ix_cryptobot_invoices_status', table_name='cryptobot_invoices')
    op.drop_table('cryptobot_invoices')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_index('ix_users_referrer_id', table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index('ix_services_platform_type_active', table_name='services')
    op.drop_index('ix_services_platform_active', table_name='services')
    op.drop_table('services')
    op.drop_table('required_channels')
    op.drop_table('admin_actions')
    # ### end Alembic commands ###
